server:
  port: ${PORT:8080}

spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/visuwall
    username: visuwall
    password: dev
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true